### ISSUE TITLE
Multiple Changes shown per build

### ISSUE THREAD

**Issue by ximbal** [wolfs/all-changes-plugin#1]
Is there a config setting/option to force that the changes are shown under one build, instead of them showing two or more times the Build number and the commit?

Currently we have this behavior
![2017-12-05 10_39_19-changes title jenkins](https://user-images.githubusercontent.com/19576367/33616198-38af652c-d9aa-11e7-89b0-2ab935028813.png)

And we would like to have all the commits shown together.
![22017-12-05 10_39_19-changes title jenkins](https://user-images.githubusercontent.com/19576367/33616399-cd3e45aa-d9aa-11e7-9d4f-4885bc8889a5.png)

:
I appreciate the help.

**Comment by wolfs** [comment]
Not that I know of. Note that I am not maintaining the plugin any more. I'll close this issue.
